### ISSUE TITLE
broken sample code

### ISSUE THREAD

**Issue by JostMigenda** [SNEWS2/snewpy#88]
After merging/renaming the SNOwGLoBES-related functions in `snewpy.snowglobes` (see #87) I’m currently updating sample code/notebooks and noticed some outdated/broken sample code.

---

`SNEWS2.0_rate_table.py` crashes with the following traceback:
```
Traceback (most recent call last):
  File "/Users/jost/Documents/Academia/SNEWS/Software/snewpy/doc/nb/SNEWS2.0_rate_table.py", line 43, in <module>
    tables = snowglobes.collate(SNOwGLoBES_path, tarredfile, detector_input=det, skip_plots=True, return_tables=True)
  File "/Users/jost/opt/anaconda3/envs/snews/lib/python3.9/site-packages/snewpy/snowglobes.py", line 1088, in collate
    add_funct(*argList1)
  File "/Users/jost/opt/anaconda3/envs/snews/lib/python3.9/site-packages/snewpy/snowglobes.py", line 962, in add_funct
    new_f.write("{0}{1}{2}{3}{4}{5}".format(key, first_space, value[0], value[1], value[2], value[3]))
IndexError: list index out of range
```
The variable at fault is `value =  ['0.0                    ', '0.0                    ']` and this happens while collating `det = "halo1"`.

---

Similarly, `TimeSeries.py` is outdated. In addition to updating the import statements, I suspect it will also require the changes in #55.

**Comment by JostMigenda** [comment]
Thinking about `TimeSeries.py`: Similar to `doc/nb/SNEWPY_examples.ipynb`, this demonstrates the full SNOwGLoBES toolchain; the differences being
1. `TimeSeries.py` has fewer comments with explanations and
2. it uses `generate_time_series()` instead of `generate_fluence()`.

It would probably be better to remove that script and add a sample line with `generate_time_series()` to `SNEWPY_examples.ipynb` instead—what do you think?
